Repository streamdevs/webhook, pull requests merged in 2020-04, with the labels that each got.

#82 Run compiled TypeScript in Heroku
  package.json
Labels: feature

#84 fix: Fix args passed to StreamLabs.alert
  src/reactions/github/fork.js
  test/routes/github/fork.spec.js
Labels: fix

#76 feat: Return response with reaction handling status
  src/reactions/github/fork.js
  src/routes/github/index.js
  src/schemas/gitHubWebhookPayload.js
Labels: feature, fix

#90 fix: Make tsc ignore files in dist
  tsconfig.json
Labels: fix

#91 fix: Make jest ignore files in dist
  jest.config.js
Labels: fix

#106 docs: Add contributing section
  README.md
Labels: documentation

#122 chore: Disable JS compilation
  tsconfig.json
Labels: enhancement

#124 Lint TypeScript files with eslint
  .eslintrc.js
  package.json
  src/reactions/github/fork.ts
  src/reactions/github/reaction.ts
  src/routes/github/index.ts
  src/schemas/gitHubWebhookHeaders.ts
  src/schemas/gitHubWebhookPayload.ts
  src/server.ts
  src/services/StreamLabs.ts
  src/services/TwitchChat.ts
  test/routes/github/fork.spec.ts
  test/routes/github/ping.spec.ts
  test/routes/github/pull_request.spec.ts
  test/routes/github/star.spec.ts
  test/services/StreamLabs.spec.ts
  yarn.lock
Labels: enhancement, technical debt

#129 feat: new 'IssueOpened' reaction
  src/reactions/github/issue-opened.ts
  src/schemas/github/issue-payload.ts
  test/reactions/github/issue-opened.spec.ts
Labels: feature

#130 fix: Formatted / linted files are not added to git
  husky.config.js
  lint-staged.config.js
  package.json
  yarn.lock
Labels: enhancement, fix

#141 feature: Opt-int branch-specific notifications
  README.md
  app.json
  src/config.ts
  src/reactions/github/check-run.ts
  src/reactions/github/reaction.ts
  test/reactions/github/check-run.spec.ts
Labels: feature
